services:
  backend:
    build: ./Backend
    container_name: dbms-Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/src:/app/src          # código fuente (hot-reload)
      - ./Backend/data:/app/data        # ← AGREGAR ESTO para persistencia
      - ./Backend/src/dbms:/app/src/dbms
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./front-base
    container_name: dbms-frontend
    ports:
      - "3000:3000"
    depends_on:
      - Backend